version: 2.1
jobs:
  upload-to-venus:
    docker:
      image: circleci/node:10.16.3
    steps:
      - run: make ssh-ok
      - run: make get-code
      - run: make update-frontend
      - run: make upload-backend
      - run: make repair-permissions

workflows:
  CD:
    jobs:
      - upload-to-venus:
        filters:
          branches:
            only:
              - master